//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AplicacionWebMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AdjuntoMateriales
    {
        public int idAdjunto { get; set; }
        public int idMaterial { get; set; }
        public string nombre { get; set; }
        public string descripcion { get; set; }
    
        public virtual Materiales Materiales { get; set; }
    }
}
