//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AplicacionWebMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Configuracion
    {
        public int ejercicio { get; set; }
        public string descripcion { get; set; }
        public string identificacion { get; set; }
        public Nullable<double> version { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
        public string correoEnvia { get; set; }
        public string correoRecibe { get; set; }
        public string contrasenaCorreoE { get; set; }
        public Nullable<int> puerto { get; set; }
        public string host { get; set; }
    }
}
