//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AplicacionWebMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cotizacion_Requisiciones
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Cotizacion_Requisiciones()
        {
            this.DetallesCotizacion = new HashSet<DetallesCotizacion>();
        }
    
        public int idCotizacion { get; set; }
        public Nullable<int> idProveedor { get; set; }
        public short idCondicionPago { get; set; }
        public string requisicion { get; set; }
        public Nullable<short> departamento { get; set; }
        public string area { get; set; }
        public string ciclo { get; set; }
        public string proveedor { get; set; }
        public Nullable<System.DateTime> fechaCotizacion { get; set; }
        public string descripcionCondicion { get; set; }
        public string libreAbordo { get; set; }
        public Nullable<decimal> descuento { get; set; }
        public Nullable<short> garantia { get; set; }
        public Nullable<decimal> anticipo { get; set; }
        public Nullable<bool> apoyoTecnico { get; set; }
        public Nullable<bool> estatus { get; set; }
        public string observaciones { get; set; }
    
        public virtual Proveedores Proveedores { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DetallesCotizacion> DetallesCotizacion { get; set; }
    }
}
