//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AplicacionWebMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DetallesCotizacion
    {
        public int idDetalleCotizacion { get; set; }
        public Nullable<int> idCotizacion { get; set; }
        public Nullable<int> idMaterial { get; set; }
        public Nullable<int> cantidad { get; set; }
        public string uMedida { get; set; }
        public string descripcion { get; set; }
        public Nullable<decimal> costoU { get; set; }
        public Nullable<short> tiempoEntrega { get; set; }
        public string nota { get; set; }
        public Nullable<short> partida { get; set; }
    
        public virtual Cotizacion_Requisiciones Cotizacion_Requisiciones { get; set; }
    }
}
