//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AplicacionWebMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class empleados
    {
        public short empleado { get; set; }
        public string nombre { get; set; }
        public string apellidoPaterno { get; set; }
        public string apellidoMaterno { get; set; }
        public Nullable<System.DateTime> fechaNacimiento { get; set; }
        public string sexo { get; set; }
        public string curp { get; set; }
        public string rfc { get; set; }
        public string imss { get; set; }
        public string tipoSangre { get; set; }
        public string padecimientos { get; set; }
        public string eMail { get; set; }
        public string calle { get; set; }
        public string numeroExterior { get; set; }
        public string numeroInterior { get; set; }
        public string colonia { get; set; }
        public string cp { get; set; }
        public string localidad { get; set; }
        public string ciudad { get; set; }
        public string estado { get; set; }
        public Nullable<bool> credencial { get; set; }
        public string foto { get; set; }
        public string tipo { get; set; }
        public string contrasena { get; set; }
        public Nullable<bool> verificado { get; set; }
    }
}
