//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AplicacionWebMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Materiales
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Materiales()
        {
            this.DetalleRequisicion = new HashSet<DetalleRequisicion>();
        }
    
        public int idMaterial { get; set; }
        public int materialesCont { get; set; }
        public string uMedida { get; set; }
        public string descripcion { get; set; }
        public Nullable<decimal> maximo { get; set; }
        public Nullable<decimal> minimo { get; set; }
        public Nullable<decimal> costoProm { get; set; }
        public Nullable<decimal> costoPromAnt { get; set; }
        public Nullable<decimal> importe { get; set; }
        public Nullable<decimal> existencia { get; set; }
        public string localizacion { get; set; }
        public Nullable<decimal> cantIni { get; set; }
        public Nullable<decimal> importeIni { get; set; }
        public Nullable<System.DateTime> fechaUltimoMov { get; set; }
        public bool seguridadInd { get; set; }
        public Nullable<decimal> puntoPedido { get; set; }
        public Nullable<decimal> pedidoEstandar { get; set; }
        public bool herramienta { get; set; }
        public string marca { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DetalleRequisicion> DetalleRequisicion { get; set; }
        public virtual MaterialesContable MaterialesContable { get; set; }
    }
}
