//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AplicacionWebMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MaterialesContable
    {
        public int idMaterialesCont { get; set; }
        public Nullable<int> idMaterial { get; set; }
        public Nullable<int> cuenta_F_Z { get; set; }
        public Nullable<bool> aplicaCentCost_F_Z { get; set; }
        public Nullable<int> subCuenta_F_Z { get; set; }
        public Nullable<int> subSubCuenta_F_Z { get; set; }
        public Nullable<int> cuenta_A_Z { get; set; }
        public Nullable<bool> aplicaCentCost_A_Z { get; set; }
        public Nullable<int> subCuenta_A_Z { get; set; }
        public Nullable<int> subSubCuenta_A_Z { get; set; }
        public Nullable<int> cuenta_C_Z { get; set; }
        public Nullable<bool> aplicaCentCost_C_Z { get; set; }
        public Nullable<int> subCuenta_C_Z { get; set; }
        public Nullable<int> subSubCuenta_C_Z { get; set; }
        public Nullable<int> cuenta_D_Z { get; set; }
        public Nullable<bool> aplicaCentCost_D_Z { get; set; }
        public Nullable<int> subCuenta_D_Z { get; set; }
        public Nullable<int> subSubCuenta_D_Z { get; set; }
        public Nullable<int> cuenta_F_R { get; set; }
        public Nullable<bool> aplicaCentCost_F_R { get; set; }
        public Nullable<int> subCuenta_F_R { get; set; }
        public Nullable<int> subSubCuenta_F_R { get; set; }
        public Nullable<int> cuenta_A_R { get; set; }
        public Nullable<bool> aplicaCentCost_A_R { get; set; }
        public Nullable<int> subCuenta_A_R { get; set; }
        public Nullable<int> subSubCuenta_A_R { get; set; }
        public Nullable<int> cuenta_C_R { get; set; }
        public Nullable<bool> aplicaCentCost_C_R { get; set; }
        public Nullable<int> subCuenta_C_R { get; set; }
        public Nullable<int> subSubCuenta_C_R { get; set; }
        public Nullable<int> cuenta_D_R { get; set; }
        public Nullable<bool> aplicaCentCost_D_R { get; set; }
        public Nullable<int> subCuenta_D_R { get; set; }
        public Nullable<int> subSubCuenta_D_R { get; set; }
    
        public virtual Materiales Materiales { get; set; }
    }
}
