//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AplicacionWebMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MaterialesContable
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MaterialesContable()
        {
            this.Materiales = new HashSet<Materiales>();
        }
    
        public int idMaterialesCont { get; set; }
        public string lugar { get; set; }
        public string tipo { get; set; }
        public Nullable<int> cuenta { get; set; }
        public Nullable<bool> aplicaCentCostob { get; set; }
        public Nullable<int> subCuenta { get; set; }
        public Nullable<int> subSubCuenta { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Materiales> Materiales { get; set; }
    }
}
