//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AplicacionWebMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SubGrupos
    {
        public short grupo { get; set; }
        public short subGrupo { get; set; }
        public string descripcion { get; set; }
    
        public virtual GpoMateriales GpoMateriales { get; set; }
    }
}
